# Generated by Django 4.2.6 on 2023-10-30 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('key', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAppAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_token', models.CharField(max_length=255)),
                ('token_expiration', models.DateTimeField()),
                ('first_access', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Access Since')),
                ('last_access', models.DateTimeField(verbose_name='Last Activity')),
                ('logged_in', models.BooleanField(default=False, verbose_name='Logged In')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_authentication.app')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_authentication.user')),
            ],
        ),
    ]
