# Generated by Django 4.2.6 on 2023-10-31 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userappaccess',
            name='logged_in',
        ),
        migrations.RemoveField(
            model_name='userappaccess',
            name='token_expiration',
        ),
        migrations.RemoveField(
            model_name='userappaccess',
            name='valid_token',
        ),
    ]
